# Generated by Django 5.0.3 on 2024-03-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedcontacts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fav_contacts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feature_flag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
