# Generated by Django 5.0.3 on 2024-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_contact_delete_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
