# Generated by Django 5.0.3 on 2024-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_contact_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
