# Generated by Django 5.0.3 on 2024-03-21 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_contact_number_feature_flag_contact_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourates',
            new_name='Favourites',
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.IntegerField(),
        ),
    ]
