# Generated by Django 5.0.3 on 2024-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_contact_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedcontacts',
            name='country_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
