# Generated by Django 5.0.3 on 2024-03-22 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_deletedcontacts_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'contact_name', 'contact_number')},
        ),
    ]
