# Generated by Django 5.0.3 on 2024-04-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_feature_flag_dark_mode_feature_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deletedcontacts',
            unique_together=set(),
        ),
    ]
